Deliverys/Controllers/ExitProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.AddExit;

namespace Deliverys.Controllers
{
    public class ExitProductController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();

        // GET: ExitProduct
        public ActionResult Index()
        {
            return View(db.ExitProductModels.ToList());
        }

        // GET: ExitProduct/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            if (exitProductModel == null)
            {
                return HttpNotFound();
            }
            return View(exitProductModel);
        }

        // GET: ExitProduct/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExitProduct/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idexit,salidaentrega,iddelivery,idorder")] ExitProductModel exitProductModel)
        {
            if (ModelState.IsValid)
            {
                var idproduct = db.OdersModels.Where(w => w.idorder == exitProductModel.idorder)
                    .Select(s => new { s.idproduct, s.cantidad }).FirstOrDefault();
                var updateInventory = db.inventario.Find(idproduct.idproduct);
                updateInventory.stock = updateInventory.stock - idproduct.cantidad;
                db.Entry(updateInventory).State = EntityState.Modified;
                db.SaveChanges();

                db.ExitProductModels.Add(exitProductModel);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(exitProductModel);
        }

        // GET: ExitProduct/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            if (exitProductModel == null)
            {
                return HttpNotFound();
            }
            return View(exitProductModel);
        }

        // POST: ExitProduct/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idexit,salidaentrega,iddelivery,idorder")] ExitProductModel exitProductModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exitProductModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exitProductModel);
        }

        // GET: ExitProduct/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            if (exitProductModel == null)
            {
                return HttpNotFound();
            }
            return View(exitProductModel);
        }

        // POST: ExitProduct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            db.ExitProductModels.Remove(exitProductModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Controllers/LoginController.cs
using Deliverys.Context;
using Deliverys.Models.Home;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Deliverys.Controllers
{
    public class LoginController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();        

        public ActionResult IndexClient()
        {
            return View();
        }

        public ActionResult IndexUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginUser([Bind(Include = "iduser,nombre,apellido,telefono,correo,contrasea,direccion")] RegisterModel registerModel)
        {
            if (registerModel.correo == null && registerModel.contrasea == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var Login = db.registrar
                .Where(w => w.correo == registerModel.correo && w.contrasea == registerModel.contrasea)
                .Select(s => new { s.tipopersona , s.iduser})
                .FirstOrDefault();

            GetInformation.getId(Login.iduser);
            if(Login.tipopersona.Equals(null))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            else if(Login.tipopersona.Equals(true))
                return RedirectToAction("IndexClient");
            else
                return RedirectToAction("IndexUser");
        }

        public ActionResult LoginUser()
        {
            return View();
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Controllers/OdersController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.Orders;

namespace Deliverys.Controllers
{
    public class OdersController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();
        public static int id;

        // GET: Oders
        public ActionResult Index()
        {
            id = int.Parse(GetInformation.GlobalID);
            return View(db.OdersModels.ToList());
        }

        // GET: Oders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdersModel odersModel = db.OdersModels.Find(id);
            if (odersModel == null)
            {
                return HttpNotFound();
            }
            return View(odersModel);
        }

        // GET: Oders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Oders/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idorder,iduser,idproduct,cantidad")] OdersModel odersModel)
        {
            if (ModelState.IsValid)
            {
                var create = new OdersModel();
                create.iduser = int.Parse(GetInformation.GlobalID);
                create.idproduct = odersModel.idproduct;
                create.cantidad = odersModel.cantidad;
                db.OdersModels.Add(create);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(odersModel);
        }

        // GET: Oders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdersModel odersModel = db.OdersModels.Find(id);
            if (odersModel == null)
            {
                return HttpNotFound();
            }
            return View(odersModel);
        }

        // POST: Oders/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idorder,iduser,idproduct,cantidad")] OdersModel odersModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(odersModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(odersModel);
        }

        // GET: Oders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdersModel odersModel = db.OdersModels.Find(id);
            if (odersModel == null)
            {
                return HttpNotFound();
            }
            return View(odersModel);
        }

        // POST: Oders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OdersModel odersModel = db.OdersModels.Find(id);
            db.OdersModels.Remove(odersModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Views/Oders/Create.cshtml
@model Deliverys.Models.Orders.OdersModel

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

@{
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Registrando pedido</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })        
        <div class="form-group">
            @Html.LabelFor(model => model.idproduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idproduct, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idproduct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Pedido" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "IndexClient", "Login")
</div>

Deliverys/Views/Oders/Index.cshtml
@model IEnumerable<Deliverys.Models.Orders.OdersModel>

@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>Listado de pedidos</h2>    
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idorder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.iduser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.idproduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantidad)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.idorder)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.iduser)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.idproduct)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cantidad)
                </td>
            </tr>
        }
    </table>
    <p>
        @Html.ActionLink("Regresar", "Create", "ExitProduct")
    </p>
</body>
</html>