Deliverys/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.Delivery;

namespace Deliverys.Controllers
{
    public class DeliveryController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();

        // GET: Delivery
        public ActionResult Index()
        {
            return View(db.delivery.ToList());
        }

        // GET: Delivery/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryModel deliveryModel = db.delivery.Find(id);
            if (deliveryModel == null)
            {
                return HttpNotFound();
            }
            return View(deliveryModel);
        }

        // GET: Delivery/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Delivery/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "iddelivery,nombreDelivery,apellidoDelivery,DPI,telefono,tipoVehiculo,correoDelivery")] DeliveryModel deliveryModel)
        {
            if (ModelState.IsValid)
            {
                db.delivery.Add(deliveryModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(deliveryModel);
        }

        // GET: Delivery/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryModel deliveryModel = db.delivery.Find(id);
            if (deliveryModel == null)
            {
                return HttpNotFound();
            }
            return View(deliveryModel);
        }

        // POST: Delivery/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "iddelivery,nombreDelivery,apellidoDelivery,DPI,telefono,tipoVehiculo,correoDelivery")] DeliveryModel deliveryModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deliveryModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deliveryModel);
        }

        // GET: Delivery/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryModel deliveryModel = db.delivery.Find(id);
            if (deliveryModel == null)
            {
                return HttpNotFound();
            }
            return View(deliveryModel);
        }

        // POST: Delivery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DeliveryModel deliveryModel = db.delivery.Find(id);
            db.delivery.Remove(deliveryModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Controllers/ExitProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.AddExit;

namespace Deliverys.Controllers
{
    public class ExitProductController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();

        // GET: ExitProduct
        public ActionResult Index()
        {
            return View(db.ExitProductModels.ToList());
        }

        // GET: ExitProduct/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            if (exitProductModel == null)
            {
                return HttpNotFound();
            }
            return View(exitProductModel);
        }

        // GET: ExitProduct/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExitProduct/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idexit,salidaentrega,iddelivery,idorder")] ExitProductModel exitProductModel)
        {
            if (ModelState.IsValid)
            {
                var idproduct = db.OdersModels.Where(w => w.idorder == exitProductModel.idorder)
                    .Select(s => new { s.idproduct, s.cantidad }).FirstOrDefault();
                var updateInventory = db.inventario.Find(idproduct.idproduct);
                updateInventory.stock = updateInventory.stock - idproduct.cantidad;
                db.Entry(updateInventory).State = EntityState.Modified;
                db.SaveChanges();

                db.ExitProductModels.Add(exitProductModel);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(exitProductModel);
        }

        // GET: ExitProduct/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            if (exitProductModel == null)
            {
                return HttpNotFound();
            }
            return View(exitProductModel);
        }

        // POST: ExitProduct/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idexit,salidaentrega,iddelivery,idorder")] ExitProductModel exitProductModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exitProductModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exitProductModel);
        }

        // GET: ExitProduct/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            if (exitProductModel == null)
            {
                return HttpNotFound();
            }
            return View(exitProductModel);
        }

        // POST: ExitProduct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExitProductModel exitProductModel = db.ExitProductModels.Find(id);
            db.ExitProductModels.Remove(exitProductModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Controllers/InventoryController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.Inventory;

namespace Deliverys.Controllers
{
    public class InventoryController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();

        // GET: Inventory
        public ActionResult Index()
        {
            return View(db.inventario.ToList());
        }

        // GET: Inventory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryModel inventoryModel = db.inventario.Find(id);
            if (inventoryModel == null)
            {
                return HttpNotFound();
            }
            return View(inventoryModel);
        }

        // GET: Inventory/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventory/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idproduct,product,description,stock")] InventoryModel inventoryModel)
        {
            if (ModelState.IsValid)
            {
                db.inventario.Add(inventoryModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inventoryModel);
        }

        // GET: Inventory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryModel inventoryModel = db.inventario.Find(id);
            if (inventoryModel == null)
            {
                return HttpNotFound();
            }
            return View(inventoryModel);
        }

        // POST: Inventory/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idproduct,product,description,stock")] InventoryModel inventoryModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventoryModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inventoryModel);
        }

        // GET: Inventory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryModel inventoryModel = db.inventario.Find(id);
            if (inventoryModel == null)
            {
                return HttpNotFound();
            }
            return View(inventoryModel);
        }

        // POST: Inventory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InventoryModel inventoryModel = db.inventario.Find(id);
            db.inventario.Remove(inventoryModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Controllers/OdersController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.Orders;

namespace Deliverys.Controllers
{
    public class OdersController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();
        public static int id;

        // GET: Oders
        public ActionResult Index()
        {
            id = int.Parse(GetInformation.GlobalID);
            return View(db.OdersModels.ToList());
        }

        // GET: Oders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdersModel odersModel = db.OdersModels.Find(id);
            if (odersModel == null)
            {
                return HttpNotFound();
            }
            return View(odersModel);
        }

        // GET: Oders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Oders/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idorder,iduser,idproduct,cantidad")] OdersModel odersModel)
        {
            if (ModelState.IsValid)
            {
                var create = new OdersModel();
                create.iduser = int.Parse(GetInformation.GlobalID);
                create.idproduct = odersModel.idproduct;
                create.cantidad = odersModel.cantidad;
                db.OdersModels.Add(create);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(odersModel);
        }

        // GET: Oders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdersModel odersModel = db.OdersModels.Find(id);
            if (odersModel == null)
            {
                return HttpNotFound();
            }
            return View(odersModel);
        }

        // POST: Oders/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idorder,iduser,idproduct,cantidad")] OdersModel odersModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(odersModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(odersModel);
        }

        // GET: Oders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdersModel odersModel = db.OdersModels.Find(id);
            if (odersModel == null)
            {
                return HttpNotFound();
            }
            return View(odersModel);
        }

        // POST: Oders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OdersModel odersModel = db.OdersModels.Find(id);
            db.OdersModels.Remove(odersModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pídelo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pídelo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Todos los derechos reservados. www.pidelo.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Deliverys/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cerrar Sesón", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pedidos", "Create", "Oders")</li>
                    <li>@Html.ActionLink("Productos", "Index", "InventoryClient")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Todos los Derechos Reservados. www.pidelo.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Deliverys/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cerrar Sesión", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inventario", "Index", "Inventory")</li>
                    <li>@Html.ActionLink("Usuarios", "Index", "RegisterUser")</li>
                    <li>@Html.ActionLink("Envíos", "Create", "ExitProduct")</li>
                    <li>@Html.ActionLink("Repartidores", "Index", "Delivery")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Todos los Derechos Reservados. www.pidelo.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>