Deliverys/Controllers/InventoryClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.Inventory;

namespace Deliverys.Controllers
{
    public class InventoryClientController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();

        // GET: InventoryClient
        public ActionResult Index()
        {
            return View(db.inventario.ToList());
        }

        // GET: InventoryClient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryModel inventoryModel = db.inventario.Find(id);
            if (inventoryModel == null)
            {
                return HttpNotFound();
            }
            return View(inventoryModel);
        }

        // GET: InventoryClient/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InventoryClient/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idproduct,product,description,stock")] InventoryModel inventoryModel)
        {
            if (ModelState.IsValid)
            {
                db.inventario.Add(inventoryModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inventoryModel);
        }

        // GET: InventoryClient/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryModel inventoryModel = db.inventario.Find(id);
            if (inventoryModel == null)
            {
                return HttpNotFound();
            }
            return View(inventoryModel);
        }

        // POST: InventoryClient/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idproduct,product,description,stock")] InventoryModel inventoryModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventoryModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inventoryModel);
        }

        // GET: InventoryClient/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryModel inventoryModel = db.inventario.Find(id);
            if (inventoryModel == null)
            {
                return HttpNotFound();
            }
            return View(inventoryModel);
        }

        // POST: InventoryClient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InventoryModel inventoryModel = db.inventario.Find(id);
            db.inventario.Remove(inventoryModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Views/InventoryClient/Details.cshtml
@model Deliverys.Models.Inventory.InventoryModel

@{
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalle de producto</title>
</head>
<body>
    <div>
        <h2>Detalle de producto</h2>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.product)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.product)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.stock)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.stock)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Regresar", "Index", "InventoryClient")
    </p>
</body>
</html>

Deliverys/Views/InventoryClient/Index.cshtml
@model IEnumerable<Deliverys.Models.Inventory.InventoryModel>

@{
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Lista de productos</title>
</head>
<body>
    <h2>Productos disponibles</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idproduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.stock)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.idproduct)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.stock)
                </td>
                <td>
                    @Html.ActionLink("Detalles", "Details", new { id = item.idproduct })
                </td>
            </tr>
        }
    </table>
</body>
</html>