Deliverys/Controllers/LoginController.cs
using Deliverys.Context;
using Deliverys.Models.Home;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Deliverys.Controllers
{
    public class LoginController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();        

        public ActionResult IndexClient()
        {
            return View();
        }

        public ActionResult IndexUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginUser([Bind(Include = "iduser,nombre,apellido,telefono,correo,contrasea,direccion")] RegisterModel registerModel)
        {
            if (registerModel.correo == null && registerModel.contrasea == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var Login = db.registrar
                .Where(w => w.correo == registerModel.correo && w.contrasea == registerModel.contrasea)
                .Select(s => new { s.tipopersona , s.iduser})
                .FirstOrDefault();

            GetInformation.getId(Login.iduser);
            if(Login.tipopersona.Equals(null))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            else if(Login.tipopersona.Equals(true))
                return RedirectToAction("IndexClient");
            else
                return RedirectToAction("IndexUser");
        }

        public ActionResult LoginUser()
        {
            return View();
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Controllers/RegisterClientController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Deliverys.Context;
using Deliverys.Models.Home;

namespace Deliverys.Controllers
{
    public class RegisterClientController : Controller
    {
        private PostsqldbContext db = new PostsqldbContext();

        // GET: RegisterClient
        public ActionResult Index()
        {
            return View(db.registrar.ToList());
        }

        // GET: RegisterClient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterModel registerModel = db.registrar.Find(id);
            if (registerModel == null)
            {
                return HttpNotFound();
            }
            return View(registerModel);
        }

        // GET: RegisterClient/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RegisterClient/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "iduser,nombre,apellido,telefono,correo,contrasea,direccion")] RegisterModel registerModel)
        {
            if (ModelState.IsValid)
            {
                registerModel.tipopersona = true;
                db.registrar.Add(registerModel);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(registerModel);
        }

        // GET: RegisterClient/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterModel registerModel = db.registrar.Find(id);
            if (registerModel == null)
            {
                return HttpNotFound();
            }
            return View(registerModel);
        }

        // POST: RegisterClient/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "iduser,nombre,apellido,telefono,correo,contrasea,direccion")] RegisterModel registerModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registerModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(registerModel);
        }

        // GET: RegisterClient/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterModel registerModel = db.registrar.Find(id);
            if (registerModel == null)
            {
                return HttpNotFound();
            }
            return View(registerModel);
        }

        // POST: RegisterClient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RegisterModel registerModel = db.registrar.Find(id);
            db.registrar.Remove(registerModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Deliverys/Views/Login/IndexClient.cshtml
@{
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="jumbotron">
    <h1>Bienvenido a </h1>
    <p class="lead">Pídelo.com</p>
</div>

Deliverys/Views/Login/IndexUser.cshtml
@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


    <div class="jumbotron">
        <h1>Bienvenido a </h1>
        <p class="lead">Pídelo.com</p>
    </div>

Deliverys/Views/Login/LoginUser.cshtml
<!DOCTYPE html>
<head>
    <title>Structured Content </title>
    <link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    @model Deliverys.Models.Home.RegisterModel

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h2>Iniciando Sesión</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.contrasea, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.contrasea, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.contrasea, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Iniciar Sesión" class="btn btn-info" />
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Registrarse", "Create", "RegisterClient")
        </div>
    }
</body>